# 数据源
spring:
    datasource:
       # master数据源配置
       master:
           driverClassName: com.mysql.jdbc.Driver
           url: jdbc:mysql://39.106.251.5:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
           username: root
           password: W%PTWSLQK3xcoh3
       # cluster数据源配置
       cluster:
           driverClassName: com.mysql.jdbc.Driver
           url: jdbc:mysql://39.107.25.250:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
           username: root
           password: jie8#jlfsjd
           
